                                          PHASE-1 PREDICTION

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [4]:
dataset=pd.read_csv("LoanApprovalPrediction.csv")

In [5]:
dataset

Loan_ID  Gender Married  Dependents     Education Self_Employed  \
0    LP001002    Male      No         0.0      Graduate            No   
1    LP001003    Male     Yes         1.0      Graduate            No   
2    LP001005    Male     Yes         0.0      Graduate           Yes   
3    LP001006    Male     Yes         0.0  Not Graduate            No   
4    LP001008    Male      No         0.0      Graduate            No   
..        ...     ...     ...         ...           ...           ...   
593  LP002978  Female      No         0.0      Graduate            No   
594  LP002979    Male     Yes         3.0      Graduate            No   
595  LP002983    Male     Yes         1.0      Graduate            No   
596  LP002984    Male     Yes         2.0      Graduate            No   
597  LP002990  Female      No         0.0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
593             2900                0.0        71.0             360.0   
594             4106                0.0        40.0             180.0   
595             8072              240.0       253.0             360.0   
596             7583                0.0       187.0             360.0   
597             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
593             1.0         Rural           Y  
594             1.0         Rural           Y  
595             1.0         Urban           Y  
596             1.0         Urban           Y  
597             0.0     Semiurban           N  

[598 rows x 13 columns]

In [6]:
for columnName in dataset.columns:
    if(dataset[columnName].dtype=='O'):
        print(columnName)
        print(dataset[columnName].value_counts())

Loan_ID
LP002211    1
LP002555    1
LP001936    1
LP001465    1
LP002794    1
           ..
LP001422    1
LP002453    1
LP002990    1
LP002328    1
LP001578    1
Name: Loan_ID, Length: 598, dtype: int64
Gender
Male      487
Female    111
Name: Gender, dtype: int64
Married
Yes    388
No     210
Name: Married, dtype: int64
Education
Graduate        465
Not Graduate    133
Name: Education, dtype: int64
Self_Employed
No     488
Yes    110
Name: Self_Employed, dtype: int64
Property_Area
Semiurban    225
Urban        198
Rural        175
Name: Property_Area, dtype: int64
Loan_Status
Y    411
N    187
Name: Loan_Status, dtype: int64


Converting categorical data to numerical data

In [7]:
dataset.Gender=dataset.Gender.replace({"Male" : 1,"Female":0})
dataset.Married=dataset.Married.replace({"Yes" : 1,"No":0})
dataset.Education=dataset.Education.replace({"Graduate" : 1,"Not Graduate":0})
dataset.Self_Employed=dataset.Self_Employed.replace({"Yes" : 1,"No":0})
dataset.Loan_Status=dataset.Loan_Status.replace({"Y":1,"N":0})








In [8]:
dataset

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0    LP001002       1        0         0.0          1              0   
1    LP001003       1        1         1.0          1              0   
2    LP001005       1        1         0.0          1              1   
3    LP001006       1        1         0.0          0              0   
4    LP001008       1        0         0.0          1              0   
..        ...     ...      ...         ...        ...            ...   
593  LP002978       0        0         0.0          1              0   
594  LP002979       1        1         3.0          1              0   
595  LP002983       1        1         1.0          1              0   
596  LP002984       1        1         2.0          1              0   
597  LP002990       0        0         0.0          1              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
593             2900                0.0        71.0             360.0   
594             4106                0.0        40.0             180.0   
595             8072              240.0       253.0             360.0   
596             7583                0.0       187.0             360.0   
597             4583                0.0       133.0             360.0   

     Credit_History Property_Area  Loan_Status  
0               1.0         Urban            1  
1               1.0         Rural            0  
2               1.0         Urban            1  
3               1.0         Urban            1  
4               1.0         Urban            1  
..              ...           ...          ...  
593             1.0         Rural            1  
594             1.0         Rural            1  
595             1.0         Urban            1  
596             1.0         Urban            1  
597             0.0     Semiurban            0  

[598 rows x 13 columns]

using label encoder classified property area column

In [9]:
from sklearn.preprocessing import LabelEncoder
for Property_Area in dataset.columns:
    le =LabelEncoder()
    dataset['Property_Area']=le.fit_transform(dataset['Property_Area'])

Checking null values present or not

In [10]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           12
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Amount_Term     14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

null values are replaced by mean of their respective columns

In [11]:
dataset["Dependents"].fillna(dataset["Dependents"].mean(),inplace=True)
dataset["LoanAmount"].fillna(dataset["LoanAmount"].mean(),inplace=True)
dataset["Loan_Amount_Term"].fillna(dataset["Loan_Amount_Term"].mean(),inplace=True)
dataset["Credit_History"].fillna(dataset["Credit_History"].mean(),inplace=True)


In [12]:
dataset.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

assigning dependent & independent

In [13]:
indep_X=dataset[['Credit_History','ApplicantIncome']]

In [14]:
dep_Y=dataset[['Loan_Status']]

splitting the data for train and test

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep_X,dep_Y,test_size=1/4,random_state=1)

In [16]:
print(x_train)

     Credit_History  ApplicantIncome
589             1.0             2400
68              0.0             4300
546             1.0             4180
4               1.0             6000
187             1.0             6033
..              ...              ...
129             1.0             2718
144             1.0             1538
72              0.0             4755
235             1.0             2510
37              1.0             4166

[448 rows x 2 columns]


In [17]:
dataset.shape

(598, 13)

setting the standard using scalar

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

we are going to build our model with logistic regression

In [19]:
from sklearn.linear_model import LogisticRegression


reg=LogisticRegression()
reg.fit(x_train,y_train)


C:\Users\admin\Anaconda3\envs\MLClustering\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\admin\Anaconda3\envs\MLClustering\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

Checking the Coefficient

In [20]:
regco=reg.coef_

In [21]:
regco

array([[1.20471099, 0.01198689]])

Checking the intercept

In [22]:
regin=reg.intercept_

In [23]:
regin

array([0.77034282])

In [24]:
y_pred=reg.predict(x_test)

In [25]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0], dtype=int64)

Accuracy score for our model

In [26]:
from sklearn.metrics import accuracy_score
score=reg.score(x_train,y_train)

In [27]:
score

0.7991071428571429

In [28]:
from sklearn.metrics import classification_report
clf=classification_report(y_test,y_pred)

In [29]:
print(clf)

              precision    recall  f1-score   support

           0       0.95      0.47      0.63        45
           1       0.81      0.99      0.89       105

    accuracy                           0.83       150
   macro avg       0.88      0.73      0.76       150
weighted avg       0.86      0.83      0.81       150



To save our model we need dump function from pickle

In [30]:
import pickle
fn='final_model.sav'
pickle.dump(reg,open(fn,'wb'))

In [32]:
loaded=pickle.load(open('final_model.sav','rb'))
result=loaded.predict([[1.0,5000]])
print (result)

[1]


PHASE-2 DEPLOYMENT

In [33]:
import pickle

LOAD THE SAVED FOR DEPLOYMENT

In [34]:
loaded=pickle.load(open('final_model.sav','rb'))

In [35]:
result=loaded.predict([[0.0,2800]])

In [36]:
result

array([1], dtype=int64)